{% set name = "pkg-about" %}
{% set version = "1.3.4" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 2ca1da84088a6fa61c692b8c97a6b071f60cf6b847fc0015fdcec2bc9d4b97ca

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=80.3.0
    - packaging >=25.0.0
    - tox >=4.25.0
    - pip
  run:
    - python >={{ python_min }}
    - setuptools >=80.3.0
    - importlib-metadata >=8.7.0
    - packaging >=25.0.0
    - tomli >=2.2.1

test:
  imports:
    - pkg_about
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/karpierz/pkg_about
  doc_url: https://pkg-about.readthedocs.io/en/latest/
  summary: Shares Python package metadata at runtime.
  license: Zlib
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
