{% set name = "pkg-about" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pkg_about-{{ version }}.zip
  sha256: d62c42f18000f7f3becc5a5bc9f40af9d5191f108574d3cae7934324616ef5f6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9.0,<4.0.0
    - setuptools >=75.1.0
    - wheel >=0.44.0
    - packaging >=24.1.0
    - tox >=4.20.0
    - pip
  run:
    - python >=3.9.0,<4.0.0
    - setuptools >=75.1.0
    - packaging >=24.1.0
    - importlib-metadata >=8.5.0
    - tomli >=2.0.1
    - docutils >=0.21.2

test:
  imports:
    - pkg_about
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/karpierz/pkg-about
  summary: Shares Python package metadata at runtime.
  license: Zlib
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
