{% set name = "pkg-about" %}
{% set version = "1.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 1320f8192fe2537d6e72c06fa4191c63d4a0bc15f5958c501fcbef01c5b83c26

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=76.0.0
    - wheel >=0.44.0
    - packaging >=24.2.0
    - tox >=4.24.2
    - pip
  run:
    - python >={{ python_min }}
    - setuptools >=76.0.0
    - packaging >=24.2.0
    - importlib-metadata >=8.6.1
    - tomli >=2.0.1
    - docutils >=0.21.2

test:
  imports:
    - pkg_about
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/karpierz/pkg_about
  doc_url: https://pkg-about.readthedocs.io/en/latest/
  summary: Shares Python package metadata at runtime.
  license: Zlib
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
