{% set name = "pkg-about" %}
{% set version = "1.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pkg_about-{{ version }}.zip
  sha256: 814da12eb887a9d234bf663f72abe56e4baf5af6ac1a020fe00a1807fa0e6572

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8.10,<4.0.0
    - setuptools >=70.1.1
    - wheel >=0.43.0
    - packaging >=24.1.0
    - tox >=4.15.1
    - pip
  run:
    - python >=3.8.10,<4.0.0
    - setuptools >=70.1.1
    - packaging >=24.1.0
    - tomli >=2.0.1

test:
  imports:
    - pkg_about
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/karpierz/pkg-about
  summary: Shares Python package metadata at runtime.
  license: Zlib
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
