{% set name = "pkg-about" %}
{% set version = "1.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pkg_about-{{ version }}.zip
  sha256: a35467130692ab7861ed39e4422bc486e699273a68155f8bc6f6c68aa71af06d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=75.1.0
    - wheel >=0.44.0
    - packaging >=24.1.0
    - tox >=4.21.2
    - pip
  run:
    - python >={{ python_min }}
    - setuptools >=75.1.0
    - packaging >=24.1.0
    - importlib-metadata >=8.5.0
    - tomli >=2.0.1
    - docutils >=0.21.2

test:
  imports:
    - pkg_about
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/karpierz/pkg_about
  doc_url: https://pkg-about.readthedocs.io/en/latest/
  summary: Shares Python package metadata at runtime.
  license: Zlib
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
