schema_version: 1

context:
  name: pkg-about
  version: "1.4.0"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 0f795cca2b228e90c3424616475381e5d528d84ae7463995fc7f660ac0c9bb13

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=80.9.0
    - packaging >=25.0.0
    - tox >=4.28.4
    - pip
  run:
    - python >=${{ python_min }}
    - setuptools >=80.9.0
    - importlib-metadata >=8.7.0
    - packaging >=25.0.0
    - tomli >=2.2.1

tests:
  - python:
      imports:
        - pkg_about
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Shares Python package metadata at runtime.
  license: Zlib
  license_file: LICENSE
  homepage: https://github.com/karpierz/pkg_about
  documentation: https://pkg-about.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - thewchan
