schema_version: 1

context:
  name: pkg-about
  version: "2.0.9"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: e2ba1581c6a6975515f3daca3e80a4aeb2b65db6c9d054182726c363e6c0a24d

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=80.9.0
    - packaging >=25.0.0
    - tox >=4.32.0
    - pip
  run:
    - python >=${{ python_min }}
    - setuptools >=80.9.0
    - typing-extensions >=4.15.0
    - packaging >=25.0.0
    - tomli >=2.3.0

tests:
  - python:
      imports:
        - pkg_about
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Shares Python package metadata at runtime.
  license: Zlib
  license_file: LICENSE
  homepage: https://github.com/karpierz/pkg_about
  documentation: https://pkg-about.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - thewchan
